### ISSUE TITLE
Create two top menus similar to original site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#10]

**Comment by tradzik** [comment]
I do not like this idea - website should look nicely, when I will add additional navbar - in this theme that will look quite strange. All links in this second top menu are already included in website

**Comment by tradzik** [comment]
@mariobehling  ping

I think we can close that

**Comment by mariobehling** [comment]
can you propose another theme that shows the FOSSASIA logo and identity more clearly? How well is the content and design seperated? Can we just exchange a theme?
