### ISSUE TITLE
"Who is coming" links are missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#11]
- Scrap original content and photos of http://2010.fossasia.org/2010/coming and sublinks (probably with script)
- Include sublinks to people
- make twitter name into link
- use structure like
- fossasia10/coming/
- fossasia10/coming/"name of participant"

**Comment by ty221** [comment]
@mariobehling ping

**Comment by mariobehling** [comment]
Honestly, I do not understand so well, why we need to create so many tasks. What is your goal of having such a large number of tasks?

**Comment by mariobehling** [comment]
http://2010.fossasia.org/2010/coming
If you click on a person's name, you will see his/her name on Twitter and Facebook. Please get those names and make them into links with icons on the new page: http://2010.fossasia.org/2010/coming
e.g. http://2010.fossasia.org/mario-behling

**Comment by mariobehling** [comment]
- Correct links of facebook and twitter
- Make name into link and use website link

**Comment by samarsault** [comment]
@mariobehling, there's no fixed format for the urls, for example some are just names while others are complete urls, and some are just after profile.php

**Comment by mariobehling** [comment]
Yeah, that's the problem. Let's fix it step by step maybe?
Complete URL's are ok.
for Links without http -> add http
For people who just added a name -> add http://facebook.com/[add name here]
Does it make sense?

**Comment by samarsault** [comment]
@mariobehling but that's a large data set, which will take a lot of time

**Comment by mariobehling** [comment]
Correct: There are two options as I see it:
a) write a script and improve scripting skills
b) Go step by step and share the work among different people, who would like to help

**Comment by samarsault** [comment]
@mariobehling, choosing the scripting way on it :)

**Comment by tradzik** [comment]
@samarjeet27 I wrote simple script to grab current data. You can use it, if you want - there you have a link: http://www.google-melange.com/gci/task/view/google/gci2014/5883234810331136

**Comment by samarsault** [comment]
@ty221, I also wrote a script for that and currently all the data is available but the problem is it's in varied formats. Also, the ^^ above script won't work as the request has to be authorised else 403 error

**Comment by tradzik** [comment]
@samarjeet27 I talked with @RoonyH  and he told me, I should grab only publicly available site and don't care about subsites. I didn't give you finished solution, just base to kick-start. @mariobehling , we need your advice here - 403 errors happen in case of most profiles. Then no script will be available to grab their data.

**Comment by samarsault** [comment]
@ty221, we already have the data we just need to get the links to work

**Comment by tradzik** [comment]
@samarjeet27 Yes, we have them already, I grabbed them. We need to make links, however it might be difficult as some links on orginal website return 403

**Comment by mariobehling** [comment]
@ty221 @samarjeet27 I gave Samarjeet access to the site. Please share privately and see, what issues you can solve. Cheers!

**Comment by samarsault** [comment]
@mariobehling, what should we do where the users have provided their emails ?

**Comment by mariobehling** [comment]
I think no need for making emails public. Good point!

**Comment by samarsault** [comment]
@mariobehling done what was possible in https://github.com/fossasia/fossasia10/pull/49

**Comment by samarsault** [comment]
@mariobehling can you look into https://github.com/fossasia/fossasia-communities/issues/90 too :)

**Comment by tradzik** [comment]
@mariobehling You can also investigate matter of adding us to FOSSASIA GCI Student as owners

**Comment by mariobehling** [comment]
Did you check,
1) if it is possible to make the FB links work and 
2) make the name link to the website?
3) How can we get rid of the confusing characters in the organization column?

**Comment by samarsault** [comment]
@mariobehling, the fb links work but a person needs to be signed in to his/her account to view that
also,for the confusing character in the org column,  I'll try removing that using regex search/replace

**Comment by mariobehling** [comment]
Ok, great. So, let's see how we can make the FB links work here http://fossasia.github.io/fossasia10/whos_coming/

**Comment by samarsault** [comment]
@mariobehling , oops sorry, I forgot to commit that https://github.com/fossasia/fossasia10/pull/50

**Comment by samarsault** [comment]
@mariobehling https://github.com/fossasia/fossasia10/pull/51 fixed the untidy org names

**Comment by samarsault** [comment]
@mariobehling can we close this ?

**Comment by mariobehling** [comment]
It would be great, if we improve the page by changing the links into icons now:
a) Website links -> Globe Icon
b) Twitter links -> Twitter Icon
c) Facebook links -> Facebook Icon
What do you think?

Then improve column width to use space more efficiently.

**Comment by samarsault** [comment]
@mariobehling Added https://github.com/fossasia/fossasia10/pull/54

**Comment by samarsault** [comment]
@mariobehling, can we close this ?

**Comment by mariobehling** [comment]
Well, we could close it or try some more improvements:
- Please only keep the globe icon and delete the URL link text "http..."
- Then improve column width to use space more efficiently.
- merge website column and social media column

**Comment by samarsault** [comment]
@mariobehling https://github.com/fossasia/fossasia10/pull/55 
are there any more improvements to be considered ?

**Comment by mariobehling** [comment]
1. Then improve column width to use space more efficiently. - last column is thin compared to content
2. If possible add scroll over effect to columns

**Comment by samarsault** [comment]
@mariobehling scroll-over to rows or columns ? rows look better I guess

**Comment by mariobehling** [comment]
rows. yes, it's the best. you understand, what looks good! right.

**Comment by samarsault** [comment]
@mariobehling done in https://github.com/fossasia/fossasia10/pull/56

**Comment by mariobehling** [comment]
Good job!
