### ISSUE TITLE
Implement clean url structure like in original site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#18]
compare
http://2010.fossasia.org/location
and
http://fossasia.github.io/fossasia10/location.html

**Comment by tradzik** [comment]
Can you show what is exactly wrong?

**Comment by mariobehling** [comment]
Goal is an html structure like that e.g. http://fossasia.github.io/fossasia10/location/

**Comment by samarsault** [comment]
@mariobehling can this be closed ?
