### ISSUE TITLE
Increase photo size to available width of area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#30]

**Comment by wongalvis** [comment]
@mariobehling From https://github.com/pwmvx1289/fossasia10/blob/gh-pages/css/main.css#L7 to https://github.com/pwmvx1289/fossasia10/blob/gh-pages/css/main.css#L20 you can see that the image size decreases when the screen size increases. This is to avoid issues caused by images with low dimensions.

**Comment by mariobehling** [comment]
We solved this issue with the 2011 site. Maybe have a look there. I will upload photos in higher dimension in the folder img/originals as well, that we can use.

**Comment by wongalvis** [comment]
@mariobehling The low dimensions images are the ones linked from external websites. Like those from http://fossasia.github.io/fossasia10/location/

**Comment by mariobehling** [comment]
Yes, you are right. We should get those here. They are mostly from Wikipedia sites and under a free license. So, let's get higher resolution from WP and host them here on Github. Could you help with this?

**Comment by mariobehling** [comment]
I have added the photos now. Please do not change the photos in the originals folder. Copy the photos into the image folder and adapt them as needed. Leave the originals untouched.

**Comment by wongalvis** [comment]
@mariobehling I think there is a problem that the dimensions of the images from Wikimedia are originally low. 
For now, I cannot any new images added.

**Comment by mariobehling** [comment]
You need to check. Most files have larger versions e.g. http://commons.wikimedia.org/wiki/File:Mother_Child_Motorbike_Vietnam.jpg

**Comment by wongalvis** [comment]
@mariobehling That is one of the images that have high resolutions and do not have the issues concerned. But for example, this image http://commons.wikimedia.org/wiki/File:Saigonnightskyline.jpg has a low dimension. A new image could be used but I'm not sure whether FOSSASIA would like to keep the content same as the original one.

**Comment by mariobehling** [comment]
Ok, let's do what is possible first and discuss open issues later.

**Comment by wongalvis** [comment]
@mariobehling I'll work on the images. :-)
