### ISSUE TITLE
Change menu order and titles as follows

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#31]
Home
Schedule
Meetings
Who's coming
Venue
Location  
Hotels
About
Contact
Blog
FOSSASIA (Dropdown menu like fossasia.org)
FOSSASIA 11
FOSSASIA 12
FOSSASIA 14
FOSSASIA 15
Mailing List -> http://groups.google.com/group/fossasia
FOSSASIA Network -> fossasia.net

**Comment by wongalvis** [comment]
Changed menu in https://github.com/fossasia/fossasia10/pull/38 and https://github.com/fossasia/fossasia10/pull/39
The mailing list and FOSSASIA Network are not added at this moment since it involves some more changes to include them within the menu bar. It will be updated asap. :-)

**Comment by mariobehling** [comment]
Looks good. Should we combine Venue, Location and Hotel in one Dropbdown Menu?
Is it possible to make the first item (Venue) on a list into a link as well?

**Comment by wongalvis** [comment]
Yes of course. :)

**Comment by wongalvis** [comment]
https://github.com/fossasia/fossasia10/pull/41

**Comment by mariobehling** [comment]
1) Click on "Venue" does not work - change back into three menu items (as we have more space again - see next point)
2) As we have two menus now, we can move the following to the very top menu on the right:
    About
    Mailing List
    Contact
3) Use a globe icon or something similar for "FOSSASIA Network" on top right menu
