### ISSUE TITLE
Fix links of sponsors/partners/venue

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#33]
A number of links seem to lead to 404 error pages, e.g. check "OpenOffice" -> http://fossasia.github.io/fossasia10/openoffice.html

**Comment by mariobehling** [comment]
@pwmvx1289 Good work, but let's try to check more if everything is correct. Please do not use Google search to find some companies that might have the same name as a sponsor. Please check for correct links on the original website: http://web-essentials.asia is the correct link for example. Keep it up! Thank you!

**Comment by wongalvis** [comment]
@mariobehling I've been trying to search for the most correct one out of many organizations with the same name. For web essentials I couldn't find the correct one on Google even if I search with the logo. I'll make them more accurate with my best efforts.

**Comment by wongalvis** [comment]
@mariobehling Turns out that the link targets appear to be content in the .md files.
Links fixed in https://github.com/fossasia/fossasia10/pull/37
