### ISSUE TITLE
Expand sidebar blocks in small screen version to available width

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#34]
![screenshot from 2015-01-18 16 31 09](https://cloud.githubusercontent.com/assets/1583873/5792923/89ce764a-9f2f-11e4-8bf3-19cb1228d36c.png)

**Comment by wongalvis** [comment]
The Twitter feed is able to be made responsive but the Facebook like box has a static width which is quite troublesome to make it responsive. I'm researching to see if there are ways to improve it.

**Comment by wongalvis** [comment]
Solved in https://github.com/fossasia/fossasia10/pull/38

**Comment by mariobehling** [comment]
Please see below. Tested on Firefox.
![screenshot from 2015-01-19 10 40 01](https://cloud.githubusercontent.com/assets/1583873/5798457/966effee-9fc7-11e4-9e16-9091842acc4a.png)

**Comment by wongalvis** [comment]
@mariobehling Thank you for reporting that, it is not observable in Chrome and I haven't been aware of that until now. It's fixed in https://github.com/fossasia/fossasia10/pull/40
