### ISSUE TITLE
Change footer line

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#35]
Substitute "Ported from Drupal by Tymon Radzik 2015 during Google Code-In contest" by

"FOSSASIA | Fork Site on Github

 FOSSASIA with link to fossasia.org -- Fork on.. with link to https://github.com/fossasia/fossasia10

We appreciate the work of Tymon, but we also appreciate a lot of other people who worked on the original site and on this site. People can view all contributions on Github now. So this give contibutors credit.

**Comment by wongalvis** [comment]
A contributors section could be added, just saying, like a box listing out the contributors.

**Comment by wongalvis** [comment]
Changed in https://github.com/fossasia/fossasia10/pull/36
