### ISSUE TITLE
Research options to integrate github page with gravatar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#57]
What are the options to integrate gravatar with the "who is coming" page. We have the emails of people.

**Comment by samarsault** [comment]
@mariobehling, all the people haven't provided their emails only some have, and that too they've provided their facebook email. Would it really be possible ?

**Comment by mariobehling** [comment]
Hi, all emails are in the Drupal system, without it they could not have signed up. You can see the gravatar integration on the old website in action. Not sure, if/how it is possible here. That is why the task is "research".

**Comment by samarsault** [comment]
@mariobehling, from [this](https://en.gravatar.com/site/implement/images/) doc, I found that we can calculate the hash using cryptojs like

``` javascript
// calculate email hash
var email_hash = CryptoJS.MD5(email);
var user = $('.user');
// create the image element
var img = $('<img>', { src : "http://www.gravatar.com/avatar/"+email_hash });
user.append(img);
```

we can make a list of emails in the coming.json, but they are not publicly available

**Comment by tradzik** [comment]
@mariobehling @samarjeet27 Can you give me access to the website?

Sun Jan 25 2015 at 13:13:09 użytkownik Samarjeet notifications@github.com
napisał:

**Comment by mariobehling** [comment]
Yes @samarjeet27 please share the access with @ty221 to see, what solution is possible.

**Comment by samarsault** [comment]
@ty221, which site are you talking about ?

**Comment by samarsault** [comment]
@mariobehling shared :)

**Comment by samarsault** [comment]
@mariobehling, so we have an option - Add an email entry to the coming.json and use the above code for the gravatar, or we could use php for server-side interaction with the database but that's not possible because this is a jekyll site. what do you think ?

**Comment by mariobehling** [comment]
Please implement a test solution. PHP is not an option.

**Comment by samarsault** [comment]
@mariobehling, how do I access the emails of users ?

**Comment by mariobehling** [comment]
Let's work on a test solution first before exploring Drupal user accounts.

**Comment by samarjeet27** [comment]
@mariobehling, see https://github.com/samarjeet27/fossasia10/tree/jekyll-solution, wrote a jekyll plugin for that

**Comment by samarsault** [comment]
( Updated )
@mariobehling we have two solutions 
1.  this one's a complicated but elegant solution. That's not really needed but will be in the long term I guess.

Github Pages doesn't support jekyll plugins which are really useful. Added a rake task which automatically generates the site and pushes it to gh-pages using

``` sh
rake publish
```

with this, I used a simple plugin I created to generate the gravatar url using -

``` html
<img src="{{ member.website | to_gravatar }}">
```

so, **master** becomes the default branch and each time a change is pushed to master, `rake publish` is ran to update the gh-pages branch with the latest site.

Also see [master](https://github.com/samarjeet27/fossasia10/) and [gh-pages](https://github.com/samarjeet27/fossasia10/tree/gh-pages)

see it live [here](http://samarjeet27.github.io/fossasia10/whos_coming)
1. The javascript solution

using [this](https://github.com/fossasia/fossasia10/issues/57#issuecomment-71369663) code, created a simple script to add gravatars

See https://github.com/samarjeet27/fossasia10/tree/js-solution

@mariobehling, which one sounds better ?
will submit pulls accordingly.

**Comment by mariobehling** [comment]
This looks great. Could you document this in the Readme.md file, please? If I want to set it up on my own how would I do it? Secondly check how you can extract emails from Drupal users.

**Comment by samarsault** [comment]
@mariobehling, which one do you recommend the jekyll solution or the javascript one ?

**Comment by samarsault** [comment]
@mariobehling, both the js and the jekyll can be run locally using

``` sh
$ jekyll serve
```

but github-pages doesn't support jekyll plugins
so, to deploy, we need to use `rake publish`

Added Instructions here at https://github.com/samarjeet27/fossasia10/

**Comment by mariobehling** [comment]
What do you suggest now? I am leaning towards the JS solution.

**Comment by samarsault** [comment]
@mariobehling both solutions are good enough, but the js is more simpler than the jekyll one. But the jekyll one is simpler "in development" but complicated in deploying and only a person with push access can update the gh-pages branch

**Comment by samarsault** [comment]
@mariobehling, guess js solution is good to go if we have many developers working on it. it would have been a lot simpler if github-pages supported custom plugins. so, should we go with the js one ?

**Comment by tradzik** [comment]
@mariobehling Can you answer please my question about gradient?

Sun Jan 25 2015 at 17:14:33 użytkownik Samarjeet notifications@github.com
napisał:

**Comment by mariobehling** [comment]
@samarjeet27 Yes, let's go with the JS solution then. Good work!

**Comment by samarsault** [comment]
@mariobehling, ok now what's left is how to fetch the emails. Neither javascript nor jekyll can access databases so we need to add them to coming.json using a web scraping script or something but how can I access the emails ?

**Comment by tradzik** [comment]
@samarjeet27 I have idea. We can create something like PHP API, which will return JSON data. Javascript can query PHP and can parse JSON.

**Comment by samarsault** [comment]
@ty221, php is not an option according to mario, because then we will have to maintain the servers

**Comment by tradzik** [comment]
@samarjeet27 It would be hard to keep database hidden and do not use servers. However, I can give account for FOSSASIA on my VPS or we can use something like Heroku, where we get free server and PostgreSQL database (however limit is 10k rows). @mariobehling What do you think?

**Comment by samarsault** [comment]
@mariobehling, what do you think should we add the emails in the coming.json or use a web service ?

**Comment by tradzik** [comment]
@samarjeet27 @mariobehling I think adding emails to public list is not nice and could be law violation ("We never share your email to third-parties" - then we'll make emails accessible to anyone!). We should rather use a server. I offered you to ways how to get free one.

**Comment by tradzik** [comment]
We can also calculate one-time hashes of all emails, and just add these hashes to JSON file. Then query Gravatar API with JS. This is secure, and doesn't violate privacy of users. However, that will require changing our grabber-script and implementation in JS.

**Comment by samarsault** [comment]
@ty221, but one can also access the emails using the wrapper we use to get the data

**Comment by tradzik** [comment]
@samarjeet27 Do you mean server-side solution? No, because in this option, server will:
1. Query DB for email
2. Calculate hash of email
3. Query Gravatar API about Gravatar for specific hash
4. Return image

Nobody, expects server,  will have access to mails.

**Comment by tradzik** [comment]
@samarjeet27 Can you show me your grabber code? I have idea....

**Comment by samarsault** [comment]
@ty221 see https://github.com/samarjeet27/fossasia10/tree/js-solution

**Comment by samarsault** [comment]
@ty221, please show your wrapper code first

**Comment by samarsault** [comment]
let's see what @mariobehling has to say, what would be better ? adding the emails to the coming.json file or a jsonp wrapper ? also hashes could be stored in the coming.json file too

**Comment by samarsault** [comment]
@mariobehling, could you e-mail me some database dump ( csv file or something ). Maybe we could generate md5 hash for the email and store the **hashes** instead of the **emails** in the coming.json file ?

**Comment by tradzik** [comment]
@samarjeet27 I told that already, we can store hashes in coming.json, but then we'll have to change JSON file generator (code, which gathers user data)

**Comment by samarsault** [comment]
@ty221 , the 2010 event is over which means no user will be added, and I'll handle that once I get the data from mario

**Comment by mariobehling** [comment]
Hi guys, please give me some time (a couple of days or so) for the DB dump. In the meantime could you help to solve the other issues for FOSSASIA 10?

**Comment by tradzik** [comment]
@mariobehling Hi, if you want I can make this DB dump, that shouldn't be
hard for me (I am server admin and did that copule times before). I can do
that ASAP. However, for sure we'll work on other issues.

Mon Jan 26 2015 at 14:05:56 użytkownik mariobehling <
notifications@github.com> napisał:

**Comment by samarsault** [comment]
@mariobehling, ok managed to get a solution fetching data using a script

live : http://samarjeet27.github.io/fossasia10/whos_coming

see :  https://github.com/fossasia/fossasia10/pull/64
