### ISSUE TITLE
Include rich content like in original site, e.g. Google map and formatting of e.g. weather, gallery in location page etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2010.fossasia.org#8]

**Comment by mariobehling** [comment]
Please check venue page: Picture resolution 
http://ty221.github.io/fossasia10/venue.html

**Comment by tradzik** [comment]
Fixed #19

**Comment by mariobehling** [comment]
Fix weather table http://fossasia.github.io/fossasia10/location.html
compare to http://2010.fossasia.org/location
